/**
 *
 * initialState
 *
 */

export const initialState = {
  en: {
    enabled: true,
    words: [
      [
        '',
        'one',
        'two',
        'three',
        'four',
        'five',
        'six',
        'seven',
        'eight',
        'nine',
        'ten',
        'eleven',
        'twelve',
        'thirteen',
        'fourteen',
        'fifteen',
        'sixteen',
        'seventeen',
        'eighteen',
        'nineteen',
      ],
      [
        '',
        '',
        'twenty',
        'thirty',
        'forty',
        'fifty',
        'sixty',
        'seventy',
        'eighty',
        'ninety',
      ],
      [
        '',
        'one hundred',
        'two hundred',
        'three hundred',
        'four hundred',
        'five hundred',
        'six hundred',
        'seven hundred',
        'eight hundred',
        'nine hundred',
      ],
      [
        '',
        '',
        'thousand',
        'million',
        'billion',
        'trillion',
        'quadrillion',
        'quintillion',
        'sextillion',
      ],
    ],
  },

  en_us: {
    enabled: false,
    words: [
      [
        '',
        'one',
        'two',
        'three',
        'four',
        'five',
        'six',
        'seven',
        'eight',
        'nine',
        'ten',
        'eleven',
        'twelve',
        'thirteen',
        'fourteen',
        'fifteen',
        'sixteen',
        'seventeen',
        'eighteen',
        'nineteen',
      ],
      [
        '',
        '',
        'twenty',
        'thirty',
        'forty',
        'fifty',
        'sixty',
        'seventy',
        'eighty',
        'ninety',
      ],
      [
        '',
        'one hundred',
        'two hundred',
        'three hundred',
        'four hundred',
        'five hundred',
        'six hundred',
        'seven hundred',
        'eight hundred',
        'nine hundred',
      ],
      [
        '',
        '',
        'thousand',
        'million',
        'billion',
        'trillion',
        'quadrillion',
        'quintillion',
        'sextillion',
      ],
    ],
  },

  ru: {
    enabled: false,
    words: [
      [
        '',
        'один',
        'два',
        'три',
        'четыре',
        'пять',
        'шесть',
        'семь',
        'восемь',
        'девять',
        'десять',
        'одиннадцать',
        'двенадцать',
        'тринадцать',
        'четырнадцать',
        'пятнадцать',
        'шестнадцать',
        'семнадцать',
        'восемнадцать',
        'девятнадцать',
      ],
      [
        '',
        '',
        'двадцать',
        'тридцать',
        'сорок',
        'пятьдесят',
        'шестьдесят',
        'семьдесят',
        'восемьдесят',
        'девяносто',
      ],
      [
        '',
        'сто',
        'двести',
        'триста',
        'четыреста',
        'пятьсот',
        'шестьсот',
        'семьсот',
        'восемьсот',
        'девятьсот',
      ],
      [
        '',
        '',
        'тысяч',
        'миллионов',
        'миллиардов',
        'триллионов',
        'квадриллионов',
        'квинтиллионов',
        'секстиллионов',
      ],
    ],
  },

  uk: {
    enabled: false,
    words: [
      [
        '',
        'один',
        'два',
        'три',
        'чотири',
        "п'ять",
        'шість',
        'сім',
        'вісім',
        "дев'ять",
        'десять',
        'одинадцять',
        'дванадцять',
        'тринадцять',
        'чотирнадцять',
        "п'ятнадцять",
        'шістнадцять',
        'сімнадцять',
        'вісімнадцять',
        "дев'ятнадцять",
      ],
      [
        '',
        '',
        'двадцять',
        'тридцять',
        'сорок',
        "п'ятдесят",
        'шістдесят',
        'сімдесят',
        'вісімдесят',
        "дев'яносто",
      ],
      [
        '',
        'сто',
        'двісті',
        'триста',
        'чотириста',
        "п'ятсот",
        'шістсот',
        'сімсот',
        'вісімсот',
        "дев'ятсот",
      ],
      [
        '',
        '',
        'тисяч',
        'мільйонів',
        'мільярдів',
        'трильйонів',
        'квадрильйонів',
        'квінтильйонів',
        'секстильйонів',
      ],
    ],
  },
}

export default initialState
